project:
  type: book
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - sql-basics.qmd

book:
  title: "SQL Fundamentals with BigQuery"
  chapters:
    - index.qmd
    - about.qmd
    - sql-basics.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true