project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - sql-basics.qmd
website:
  title: "SQL Fundamentals with BigQuery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true