project:
  type: book
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - sql-basics.qmd

book:
  title: "SQL Fundamentals with BigQuery"
  page-footer: 
      left: "Copyright 2025, Rafael Saraiva" 
  chapters:
    - index.qmd
    - about.qmd
    - sql-basics.qmd
    - group-basics.qmd
    - sql-joins.qmd
    - organized-queries.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: 5
    number-sections: false