# The First Steps

In SQL there is a subset of knowledge that is focused on retrieving data from tables. This is called DQL (Data Query Language). 

Bigquery is a very DQL-centric database, by this way our queries are optimized to **SELECT** information (columns) from tables so we can perform analysis and use this data to help us answer questions by data-centric way.

To retrieve information from a table, we need to inform for the query engine which table we want to retrieve information **FROM**

This leads us for the most basic command to retrieve information from any SQL based databases:

```{sql}
SELECT * FROM `bigquery-public-data.openaq.global_air_quality`
```

SELECT * is known as "SELECT star" and is a way to fetch all the columns from the table. Even that this technique looks easy and without effort, it's normally not optimal to run it to queries that contains a high number os columns since it may increase the cloud cost significantly due to the usage of computational resources.

<Add figure of bq making computations>

Another important command to learn is the filtering functionality "WHERE". With this command we may filter out results for the author's analysis. For example, if we are analyzing taxi-drives, maybe we want to analyze the rides of a specific city. This can be done with the following query:

```{sql}
SELECT * FROM `bigquery-public-data.openaq.global_air_quality`
WHERE country = "BR"
```
To reduce the usage of computational resources (costs), one way is to filter the number of columns you are currently retrieving. Another way is to 
-- Sometimes you are going to be dealing with huge number of data, this is why it's important to filter, or to limit the data.

```{python}
from IPython.display import display, Markdown,  HTML
import pandas as pd
# with this I can hide the code that is used
#| echo: False

query = """
SELECT user_id, COUNT(*) as total
FROM `project.dataset.table`
WHERE event_date >= '2024-01-01'
GROUP BY user_id
ORDER BY total DESC
LIMIT 10;
"""

# Wrap it in code block markdown with SQL
display(Markdown(f"```sql\n{query}\n```"))

data = pd.DataFrame(
    [
        [1,2,1],
        [2,3,4],
        [3,4,9]
    ],
    columns = ['numbers', 'plus_one', 'square']
)

HTML(data.to_html(index=False))
```